// Note: This code was generated by AI [ChatGPT]
(async function () {
  const CONFIG = {
    REQUEST_SPACING_MS: 120,
    MAX_CONCURRENT_REQUESTS: 3,
    CACHE_LIMIT: 500,
    LOOKAHEAD_COUNT: 3,
    UI_UPDATE_INTERVAL: 100,
    POPUP_SYNC_INTERVAL: 200,
    MATCH_TOLERANCE: 0.15,
    INITIAL_RETRY_DELAY: 3000,
    RETRY_DELAY: 1500,
    MAX_RETRY_DELAY: 15000,
    BACKGROUND_FILL_DELAY: 900,
    PRIORITY_FORWARD: 20,
    PRIORITY_BACKWARD: 5
  };
  const PROGRESS_STORAGE_KEY = "translationProgress";
  const SETTINGS_STORAGE_KEY = "translationSettings";
  const DEFAULT_TARGET_LANGUAGE = "zh-CN";

  if (window.__subtitleTranslatorRunning) {
    console.warn("The script is already running. Run window.__subtitleTranslatorCleanup() before starting it again.");
    return;
  }
  window.__subtitleTranslatorRunning = true;
  let isExtensionContextValid = true;

  function writePopupState(progress) {
    if (!isExtensionContextValid) return;
    try {
      if (!chrome?.storage?.local) return;
      chrome.storage.local.set({ [PROGRESS_STORAGE_KEY]: progress });
    } catch (error) {
      const message = String(error?.message || error || "");
      if (message.includes("Extension context invalidated")) {
        isExtensionContextValid = false;
        try { window.__subtitleTranslatorCleanup?.(); } catch {}
        return;
      }
      console.warn("Failed to write popup state", error);
    }
  }

  function clearPopupState() {
    writePopupState({
      running: false,
      statusText: "Waiting for translation...",
      translated: 0,
      total: 0,
      uniqueDone: 0,
      uniqueTotal: 0,
      queueLength: 0,
      percent: 0,
      activeText: ""
    });
  }

  async function getStoredTargetLanguage() {
    try {
      if (!chrome?.storage?.local) return DEFAULT_TARGET_LANGUAGE;
      const result = await chrome.storage.local.get(SETTINGS_STORAGE_KEY);
      return result?.[SETTINGS_STORAGE_KEY]?.targetLanguage || DEFAULT_TARGET_LANGUAGE;
    } catch (error) {
      console.warn("Failed to read translation settings", error);
      return DEFAULT_TARGET_LANGUAGE;
    }
  }

  function findVttUrl() {
    const track = document.querySelector("track[kind='subtitles'], track[kind='captions']");
    if (track?.src) {
      console.log("✅ Found VTT from <track>:", track.src);
      return track.src;
    }

    const entries = performance.getEntriesByType("resource");

    for (const entry of entries) {
      if (entry.name.includes("captions") && entry.name.endsWith(".vtt")) {
        console.log("✅ Found captions VTT from network:", entry.name);
        return entry.name;
      }
    }

    for (const entry of entries) {
      if (entry.name.endsWith(".vtt")) {
        console.log("✅ Found VTT from network:", entry.name);
        return entry.name;
      }
    }

    return null;
  }

  function waitForVideo(timeoutMs = 15000) {
    return new Promise((resolve, reject) => {
      const startedAt = Date.now();
      const timer = setInterval(() => {
        const video = document.querySelector("video");
        if (video) {
          clearInterval(timer);
          resolve(video);
          return;
        }

        if (Date.now() - startedAt > timeoutMs) {
          clearInterval(timer);
          reject(new Error("Timed out waiting for video"));
        }
      }, 300);
    });
  }

  function findVideoContainer(videoElement) {
    const videoRect = videoElement.getBoundingClientRect();
    let bestContainer = videoElement.parentElement;

    for (let element = videoElement.parentElement; element && element !== document.body; element = element.parentElement) {
      const rect = element.getBoundingClientRect();
      const containsVideo = rect.width >= videoRect.width && rect.height >= videoRect.height;
      const isReasonableSize = rect.width >= 240 && rect.height >= 135;

      if (containsVideo && isReasonableSize) {
        bestContainer = element;
      }

      const name = `${element.id || ""} ${element.className || ""}`.toLowerCase();
      if (containsVideo && /\b(player|video|media|echo|presentation)\b/.test(name)) {
        return element;
      }
    }

    return bestContainer || videoElement.parentElement || document.documentElement;
  }

  function patchVideoFullscreen(videoElement) {
    const fullscreenHost = findVideoContainer(videoElement);
    if (!fullscreenHost || fullscreenHost === videoElement) return () => {};

    const methods = [
      ["requestFullscreen", "requestFullscreen"],
      ["webkitRequestFullscreen", "webkitRequestFullscreen"],
      ["webkitRequestFullScreen", "webkitRequestFullScreen"],
      ["mozRequestFullScreen", "mozRequestFullScreen"],
      ["msRequestFullscreen", "msRequestFullscreen"]
    ];
    const originals = [];

    for (const [videoMethod, hostMethod] of methods) {
      if (typeof videoElement[videoMethod] !== "function" || typeof fullscreenHost[hostMethod] !== "function") continue;
      const original = videoElement[videoMethod];
      try {
        videoElement[videoMethod] = (...args) => fullscreenHost[hostMethod](...args);
        originals.push([videoMethod, original]);
      } catch (error) {
        console.warn(`Could not patch ${videoMethod} for subtitle fullscreen overlay`, error);
      }
    }

    return () => {
      for (const [methodName, original] of originals) {
        try {
          videoElement[methodName] = original;
        } catch (error) {
          console.warn(`Could not restore ${methodName}`, error);
        }
      }
    };
  }

  function toSec(time) {
    const normalized = String(time).replace(",", ".");
    const [hours, minutes, seconds] = normalized.split(":");
    return (+hours) * 3600 + (+minutes) * 60 + parseFloat(seconds);
  }

  function isTimingLine(line) {
    return /^\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?\s*-->\s*\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?/.test(line);
  }

  function parseTimingLine(line) {
    const match = line.match(
      /^(\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?)\s*-->\s*(\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?)/
    );
    if (!match) return null;
    return {
      start: toSec(match[1]),
      end: toSec(match[2])
    };
  }

  function normalizeText(text) {
    return (text || "").replace(/\s+/g, " ").trim();
  }

  function parseVTT(vtt) {
    const lines = vtt.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
    const subtitles = [];
    let current = null;

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line || line.startsWith("WEBVTT") || line.startsWith("NOTE")) continue;
      if (line.startsWith("STYLE") || line.startsWith("REGION")) {
        current = null;
        continue;
      }

      if (isTimingLine(line)) {
        const timing = parseTimingLine(line);
        if (!timing) continue;
        current = {
          start: timing.start,
          end: timing.end,
          text: "",
          translation: null,
          status: "pending",
          error: null
        };
        subtitles.push(current);
      } else if (/^\d+$/.test(line) && !current) {
        continue;
      } else if (current) {
        current.text += line.replace(/<[^>]+>/g, "") + " ";
      }
    }

    for (const subtitle of subtitles) {
      subtitle.text = normalizeText(subtitle.text);
    }

    return subtitles.filter(subtitle => subtitle.text);
  }

  const vttUrl = findVttUrl() || await (async () => {
    console.log("VTT not found, waiting and retrying...");
    await new Promise(resolve => setTimeout(resolve, CONFIG.INITIAL_RETRY_DELAY));
    return findVttUrl();
  })();

  if (!vttUrl) {
    console.error("❌ VTT not found");
    clearPopupState();
    window.__subtitleTranslatorRunning = false;
    return;
  }

  let video;
  try {
    video = await waitForVideo();
    window.__subtitleVideo = video;
    console.log("✅ Found video:", video);
  } catch (error) {
    console.error("❌", error);
    clearPopupState();
    window.__subtitleTranslatorRunning = false;
    return;
  }
  window.__subtitleRestoreFullscreen = patchVideoFullscreen(video);

  const subtitleDiv = document.createElement("div");
  subtitleDiv.id = "__subtitle_bilingual_overlay";
  Object.assign(subtitleDiv.style, {
    position: "fixed",
    left: "50%",
    bottom: "10%",
    transform: "translateX(-50%)",
    zIndex: "2147483647",
    maxWidth: "70%",
    padding: "10px 16px",
    color: "#fff",
    background: "rgba(0,0,0,0.68)",
    borderRadius: "10px",
    fontSize: "22px",
    lineHeight: "1.45",
    textAlign: "center",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    boxShadow: "0 6px 24px rgba(0,0,0,0.35)",
    pointerEvents: "none",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif"
  });

  function getFullscreenElement() {
    return document.fullscreenElement
      || document.webkitFullscreenElement
      || document.mozFullScreenElement
      || document.msFullscreenElement
      || null;
  }

  function canHostOverlay(element) {
    if (!element || !element.appendChild) return false;
    return !["VIDEO", "IFRAME", "IMG", "CANVAS"].includes(element.tagName);
  }

  function getOverlayHost() {
    const fullscreenElement = getFullscreenElement();
    if (canHostOverlay(fullscreenElement)) return fullscreenElement;
    return document.body;
  }

  function syncOverlayHost() {
    const host = getOverlayHost();
    if (subtitleDiv.parentElement !== host) {
      host.appendChild(subtitleDiv);
    }

    Object.assign(subtitleDiv.style, {
      position: host === document.body ? "fixed" : "absolute",
      zIndex: "2147483647"
    });
  }

  syncOverlayHost();

  let subtitles = [];
  try {
    const response = await fetch(vttUrl);
    const text = await response.text();
    subtitles = parseVTT(text);
    console.log("Subtitles loaded:", subtitles.length, "entries");
  } catch (error) {
    console.error("Failed to load VTT", error);
    subtitleDiv.remove();
    clearPopupState();
    window.__subtitleTranslatorRunning = false;
    return;
  }

  if (!subtitles.length) {
    console.error("VTT parsing returned no subtitles");
    subtitleDiv.remove();
    clearPopupState();
    window.__subtitleTranslatorRunning = false;
    return;
  }

  let cursor = 0;
  let lastRenderedSubtitleText = "";

  function getSubtitleIndexByTime(time) {
    const tolerance = CONFIG.MATCH_TOLERANCE;

    while (cursor < subtitles.length - 1 && time > subtitles[cursor].end + tolerance) cursor++;
    while (cursor > 0 && time < subtitles[cursor].start - tolerance) cursor--;

    const current = subtitles[cursor];
    if (current && time >= current.start - tolerance && time <= current.end + tolerance) return cursor;

    for (let i = Math.max(0, cursor - 5); i <= Math.min(subtitles.length - 1, cursor + 5); i++) {
      const candidate = subtitles[i];
      if (time >= candidate.start - tolerance && time <= candidate.end + tolerance) {
        cursor = i;
        return i;
      }
    }

    return -1;
  }

  const engine = new window.SubtitleTranslationEngine({
    config: CONFIG,
    subtitles,
    initialLanguage: await getStoredTargetLanguage(),
    defaultLanguage: DEFAULT_TARGET_LANGUAGE,
    getCurrentIndex: () => getSubtitleIndexByTime(video.currentTime),
    onProgress: progress => writePopupState(progress)
  });

  function renderSubtitle(sub) {
    let nextText = "";

    if (sub) {
      const translation = engine.getBestTranslation(sub);
      if (translation) {
        nextText = `${sub.text}\n${translation}`;
      } else if (sub.status === "failed") {
        nextText = `${sub.text}\n(Translation failed)`;
      } else {
        nextText = `${sub.text}\n⏳ Translating...`;
      }
    }

    if (nextText !== lastRenderedSubtitleText) {
      subtitleDiv.innerText = nextText;
      lastRenderedSubtitleText = nextText;
    }
  }

  function cleanup() {
    window.__subtitleTranslatorRunning = false;
    isExtensionContextValid = false;
    try { clearInterval(window.__subtitleTimer); } catch {}
    try { engine.destroy(); } catch {}
    try { subtitleDiv.remove(); } catch {}
    try { window.__subtitleVideo?.removeEventListener("seeked", window.__subtitleOnSeeked); } catch {}
    try { window.__subtitleRestoreFullscreen?.(); } catch {}
    try { removeFullscreenListeners(); } catch {}
    try { chrome.storage.onChanged.removeListener(window.__subtitleOnStorageChange); } catch {}
    clearPopupState();
    delete window.__subtitleTranslatorCleanup;
    delete window.__subtitleTimer;
    delete window.__subtitleVideo;
    delete window.__subtitleRestoreFullscreen;
    delete window.__subtitleOnSeeked;
    delete window.__subtitleOnStorageChange;
    console.log("🧹 Script cleaned up");
  }

  window.__subtitleTranslatorCleanup = cleanup;

  function addFullscreenListeners() {
    const events = [
      "fullscreenchange",
      "webkitfullscreenchange",
      "mozfullscreenchange",
      "MSFullscreenChange"
    ];
    for (const eventName of events) {
      document.addEventListener(eventName, syncOverlayHost);
    }
  }

  function removeFullscreenListeners() {
    const events = [
      "fullscreenchange",
      "webkitfullscreenchange",
      "mozfullscreenchange",
      "MSFullscreenChange"
    ];
    for (const eventName of events) {
      document.removeEventListener(eventName, syncOverlayHost);
    }
  }

  addFullscreenListeners();

  const startIndex = getSubtitleIndexByTime(video.currentTime);
  if (startIndex !== -1) {
    console.log("✅ Built priority queue from current playback position, index =", startIndex);
  } else {
    console.log("⚠️ No subtitle matched the current playback time, falling back to the full queue");
  }
  engine.start(startIndex);

  window.__subtitleOnStorageChange = (changes, areaName) => {
    if (areaName !== "local" || !changes[SETTINGS_STORAGE_KEY]) return;
    const nextLanguage = changes[SETTINGS_STORAGE_KEY].newValue?.targetLanguage || DEFAULT_TARGET_LANGUAGE;
    engine.setTargetLanguage(nextLanguage);
    lastRenderedSubtitleText = "";
    renderSubtitle(null);
  };
  chrome.storage.onChanged.addListener(window.__subtitleOnStorageChange);

  window.__subtitleOnSeeked = () => {
    const index = getSubtitleIndexByTime(video.currentTime);
    console.log("⏩ User seeked to:", video.currentTime, "index:", index);
    engine.handleSeek(index);
  };
  video.addEventListener("seeked", window.__subtitleOnSeeked);

  let lastIndex = -1;
  window.__subtitleTimer = setInterval(() => {
    if (!window.__subtitleTranslatorRunning) return;

    const index = getSubtitleIndexByTime(video.currentTime);
    if (index === -1) {
      engine.setActiveText("");
      renderSubtitle(null);
      return;
    }

    const subtitle = subtitles[index];
    engine.setActiveText(subtitle.text);

    if (index !== lastIndex) {
      lastIndex = index;
      engine.requestImmediateTranslationForIndex(index);
      engine.boostLookahead(index);
    }

    renderSubtitle(subtitle);
  }, CONFIG.UI_UPDATE_INTERVAL);

  engine.syncProgress(true);

  console.log("Script started");
  console.log("Stop the script with: window.__subtitleTranslatorCleanup()");
})();
