// Note: This code was generated by AI [ChatGPT]
(async function () {
  const CONFIG = {
    MIN_INTERVAL: 350,
    CACHE_LIMIT: 500,
    LOOKAHEAD_COUNT: 3,
    UI_UPDATE_INTERVAL: 100,
    PROGRESS_UPDATE_INTERVAL: 300,
    MATCH_TOLERANCE: 0.15,
    INITIAL_RETRY_DELAY: 3000,
    RETRY_DELAY: 2000,
    PRIORITY_FORWARD: 20,
    PRIORITY_BACKWARD: 5
  };

  if (window.__subtitleTranslatorRunning) {
    console.warn("The script is already running. Run window.__subtitleTranslatorCleanup() before starting it again.");
    return;
  }
  window.__subtitleTranslatorRunning = true;

  function cleanup() {
    window.__subtitleTranslatorRunning = false;
    try { clearInterval(window.__subtitleTimer); } catch {}
    try { clearInterval(window.__progressTimer); } catch {}
    try { window.__subtitleWorkerAbort = true; } catch {}
    try {
      for (const timer of window.__subtitleRetryTimers?.values() || []) clearTimeout(timer);
      window.__subtitleRetryTimers?.clear?.();
    } catch {}
    try { document.getElementById("__subtitle_bilingual_overlay")?.remove(); } catch {}
    try { document.getElementById("__subtitle_translation_progress")?.remove(); } catch {}
    try { document.getElementById("__subtitle_translation_toggle")?.remove(); } catch {}
    try { window.__subtitleVideo?.removeEventListener("seeked", window.__subtitleOnSeeked); } catch {}
    try { document.removeEventListener("click", window.__subtitleOnDocumentClick); } catch {}
    try { document.removeEventListener("keydown", window.__subtitleOnDocumentKeydown); } catch {}
    delete window.__subtitleTranslatorCleanup;
    delete window.__subtitleTimer;
    delete window.__progressTimer;
    delete window.__subtitleRetryTimers;
    delete window.__subtitleVideo;
    delete window.__subtitleOnSeeked;
    delete window.__subtitleOnDocumentClick;
    delete window.__subtitleOnDocumentKeydown;
    console.log("🧹 Script cleaned up");
  }

  window.__subtitleTranslatorCleanup = cleanup;

  function findVttUrl() {
    const track = document.querySelector("track[kind='subtitles'], track[kind='captions']");
    if (track?.src) {
      console.log("✅ Found VTT from <track>:", track.src);
      return track.src;
    }

    const entries = performance.getEntriesByType("resource");

    for (const e of entries) {
      if (e.name.includes("captions") && e.name.endsWith(".vtt")) {
        console.log("✅ Found captions VTT from network:", e.name);
        return e.name;
      }
    }

    for (const e of entries) {
      if (e.name.endsWith(".vtt")) {
        console.log("✅ Found VTT from network:", e.name);
        return e.name;
      }
    }

    return null;
  }

  function waitForVideo(timeoutMs = 15000) {
    return new Promise((resolve, reject) => {
      const start = Date.now();
      const timer = setInterval(() => {
        const v = document.querySelector("video");
        if (v) {
          clearInterval(timer);
          resolve(v);
          return;
        }
        if (Date.now() - start > timeoutMs) {
          clearInterval(timer);
          reject(new Error("Timed out waiting for video"));
        }
      }, 300);
    });
  }

  function toSec(t) {
    const normalized = String(t).replace(",", ".");
    const [h, m, s] = normalized.split(":");
    return (+h) * 3600 + (+m) * 60 + parseFloat(s);
  }

  function isTimingLine(line) {
    return /^\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?\s*-->\s*\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?/.test(line);
  }

  function parseTimingLine(line) {
    const match = line.match(
      /^(\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?)\s*-->\s*(\d{2}:\d{2}:\d{2}(?:[.,]\d{3})?)/
    );
    if (!match) return null;
    return {
      start: toSec(match[1]),
      end: toSec(match[2])
    };
  }

  function normalizeText(text) {
    return (text || "").replace(/\s+/g, " ").trim();
  }

  function parseVTT(vtt) {
    const lines = vtt.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
    const subs = [];
    let cur = null;

    for (let rawLine of lines) {
      const line = rawLine.trim();
      if (!line || line.startsWith("WEBVTT") || line.startsWith("NOTE")) continue;
      if (line.startsWith("STYLE") || line.startsWith("REGION")) {
        cur = null;
        continue;
      }

      if (isTimingLine(line)) {
        const timing = parseTimingLine(line);
        if (!timing) continue;
        cur = {
          start: timing.start,
          end: timing.end,
          text: "",
          translation: null,
          status: "pending", // pending | queued | translating | done | failed
          error: null
        };
        subs.push(cur);
      } else if (/^\d+$/.test(line) && !cur) {
        // Skip cue identifiers so numeric indexes do not get merged into subtitle text.
        continue;
      } else if (cur) {
        const clean = line.replace(/<[^>]+>/g, "");
        cur.text += clean + " ";
      }
    }

    for (const s of subs) {
      s.text = normalizeText(s.text);
    }

    return subs.filter(s => s.text);
  }

  class LRUCache {
    constructor(limit = 500) {
      this.limit = limit;
      this.map = new Map();
    }
    get(key) {
      if (!this.map.has(key)) return null;
      const val = this.map.get(key);
      this.map.delete(key);
      this.map.set(key, val);
      return val;
    }
    set(key, val) {
      if (this.map.has(key)) this.map.delete(key);
      this.map.set(key, val);
      if (this.map.size > this.limit) {
        const firstKey = this.map.keys().next().value;
        this.map.delete(firstKey);
      }
    }
    has(key) {
      return this.map.has(key);
    }
    size() {
      return this.map.size;
    }
  }

  function percent(n, d) {
    if (!d) return "0.0%";
    return ((n / d) * 100).toFixed(1) + "%";
  }

  function elapsedMs(ms) {
    const s = Math.floor(ms / 1000);
    const mm = String(Math.floor(s / 60)).padStart(2, "0");
    const ss = String(s % 60).padStart(2, "0");
    return `${mm}:${ss}`;
  }

  let vttUrl = findVttUrl();
  if (!vttUrl) {
    console.log("VTT not found, waiting and retrying...");
    await new Promise(r => setTimeout(r, CONFIG.INITIAL_RETRY_DELAY));
    vttUrl = findVttUrl();
  }

  if (!vttUrl) {
    console.error("❌ VTT not found");
    cleanup();
    return;
  }

  let video;
  try {
    video = await waitForVideo();
    window.__subtitleVideo = video;
    console.log("✅ Found video:", video);
  } catch (e) {
    console.error("❌", e);
    cleanup();
    return;
  }

  const subtitleDiv = document.createElement("div");
  subtitleDiv.id = "__subtitle_bilingual_overlay";
  Object.assign(subtitleDiv.style, {
    position: "fixed",
    left: "50%",
    bottom: "10%",
    transform: "translateX(-50%)",
    zIndex: "2147483647",
    maxWidth: "70%",
    padding: "10px 16px",
    color: "#fff",
    background: "rgba(0,0,0,0.68)",
    borderRadius: "10px",
    fontSize: "22px",
    lineHeight: "1.45",
    textAlign: "center",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    boxShadow: "0 6px 24px rgba(0,0,0,0.35)",
    pointerEvents: "none",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif"
  });
  document.body.appendChild(subtitleDiv);

  const progressDiv = document.createElement("div");
  progressDiv.id = "__subtitle_translation_progress";
  Object.assign(progressDiv.style, {
    position: "fixed",
    top: "64px",
    right: "16px",
    zIndex: "2147483647",
    width: "360px",
    padding: "12px 14px",
    color: "#fff",
    background: "rgba(0,0,0,0.78)",
    borderRadius: "10px",
    fontSize: "13px",
    lineHeight: "1.5",
    whiteSpace: "pre-wrap",
    boxShadow: "0 6px 24px rgba(0,0,0,0.35)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    display: "none"
  });
  document.body.appendChild(progressDiv);

  const toggleButton = document.createElement("button");
  toggleButton.id = "__subtitle_translation_toggle";
  toggleButton.type = "button";
  toggleButton.textContent = "Translator";
  toggleButton.setAttribute("aria-expanded", "false");
  toggleButton.setAttribute("aria-controls", progressDiv.id);
  Object.assign(toggleButton.style, {
    position: "fixed",
    top: "16px",
    right: "16px",
    zIndex: "2147483647",
    padding: "8px 12px",
    border: "0",
    borderRadius: "999px",
    color: "#fff",
    background: "rgba(0,0,0,0.85)",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 6px 24px rgba(0,0,0,0.25)",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif"
  });
  document.body.appendChild(toggleButton);

  let isProgressVisible = false;
  let lastRenderedSubtitleText = "";

  function setProgressVisible(visible) {
    isProgressVisible = visible;
    progressDiv.style.display = visible ? "block" : "none";
    toggleButton.setAttribute("aria-expanded", String(visible));
    toggleButton.textContent = visible ? "Hide Translator" : "Translator";
    if (visible) renderProgress();
  }

  toggleButton.addEventListener("click", event => {
    event.stopPropagation();
    setProgressVisible(!isProgressVisible);
  });

  window.__subtitleOnDocumentClick = event => {
    if (!isProgressVisible) return;
    if (progressDiv.contains(event.target) || toggleButton.contains(event.target)) return;
    setProgressVisible(false);
  };
  document.addEventListener("click", window.__subtitleOnDocumentClick);

  window.__subtitleOnDocumentKeydown = event => {
    if (event.key === "Escape" && isProgressVisible) {
      setProgressVisible(false);
    }
  };
  document.addEventListener("keydown", window.__subtitleOnDocumentKeydown);

  const cache = new LRUCache(CONFIG.CACHE_LIMIT);

  let subtitles = [];
  try {
    const res = await fetch(vttUrl);
    const text = await res.text();
    subtitles = parseVTT(text);
    console.log("Subtitles loaded:", subtitles.length, "entries");
  } catch (e) {
    console.error("Failed to load VTT", e);
    cleanup();
    return;
  }

  if (!subtitles.length) {
    console.error("VTT parsing returned no subtitles");
    cleanup();
    return;
  }

  const stats = {
    total: subtitles.length,
    translated: 0,
    failed: 0,
    uniqueDone: 0,
    cacheHit: 0,
    requested: 0,
    currentQueueLength: 0,
    startedAt: Date.now(),
    lastTranslatedText: "",
    activeText: "",
    workerRunning: false,
    allDone: false,
    lastPriorityIndex: -1
  };

  const textToIndices = new Map();
  subtitles.forEach((sub, index) => {
    const key = sub.text;
    if (!textToIndices.has(key)) textToIndices.set(key, []);
    textToIndices.get(key).push(index);
  });

  let lastRequestTime = 0;
  window.__subtitleWorkerAbort = false;
  window.__subtitleRetryTimers = new Map();

  async function googleTranslate(text) {
    const url =
      `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=zh-CN&dt=t&q=${encodeURIComponent(text)}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    return data?.[0]?.map(x => x[0]).join("") || "";
  }

  async function translateRateLimited(text) {
    const now = Date.now();
    const wait = Math.max(0, CONFIG.MIN_INTERVAL - (now - lastRequestTime));
    if (wait > 0) await new Promise(r => setTimeout(r, wait));
    lastRequestTime = Date.now();
    stats.requested += 1;
    return googleTranslate(text);
  }

  const queue = [];
  const queuedTexts = new Set();
  const inFlightTexts = new Set();
  const scheduledUniqueTexts = new Set();
  const completedUniqueTexts = new Set();

  function markAllSameText(text, updater) {
    const indices = textToIndices.get(text) || [];
    for (const i of indices) updater(subtitles[i], i);
  }

  function updateSubtitleState(sub, nextStatus, extras = {}) {
    const prevStatus = sub.status;

    if (prevStatus === "done" && nextStatus !== "done") stats.translated -= 1;
    if (prevStatus === "failed" && nextStatus !== "failed") stats.failed -= 1;
    if (prevStatus !== "done" && nextStatus === "done") stats.translated += 1;
    if (prevStatus !== "failed" && nextStatus === "failed") stats.failed += 1;

    sub.status = nextStatus;
    if (Object.prototype.hasOwnProperty.call(extras, "translation")) sub.translation = extras.translation;
    if (Object.prototype.hasOwnProperty.call(extras, "error")) sub.error = extras.error;
  }

  function applyTranslationToAll(text, translation) {
    if (window.__subtitleRetryTimers.has(text)) {
      clearTimeout(window.__subtitleRetryTimers.get(text));
      window.__subtitleRetryTimers.delete(text);
    }

    markAllSameText(text, sub => {
      updateSubtitleState(sub, "done", { translation, error: null });
    });

    if (!completedUniqueTexts.has(text)) {
      completedUniqueTexts.add(text);
      stats.uniqueDone = completedUniqueTexts.size;
    }
  }

  function scheduleRetry(text) {
    if (window.__subtitleRetryTimers.has(text)) return;
    stats.allDone = false;

    const timer = setTimeout(() => {
      window.__subtitleRetryTimers.delete(text);
      if (!window.__subtitleTranslatorRunning) return;
      enqueueText(text, false);
    }, CONFIG.RETRY_DELAY);

    window.__subtitleRetryTimers.set(text, timer);
  }

  function markFailedForAll(text, err) {
    markAllSameText(text, sub => {
      if (sub.status !== "done") {
        updateSubtitleState(sub, "failed", { error: String(err?.message || err) });
      }
    });

    // Delay re-queueing to avoid spamming requests.
    scheduleRetry(text);
  }

  function reprioritizeQueuedText(text) {
    const normalized = normalizeText(text);
    if (!normalized) return false;
    const idx = queue.indexOf(normalized);
    if (idx <= 0) return idx === 0;
    queue.splice(idx, 1);
    queue.unshift(normalized);
    stats.currentQueueLength = queue.length;
    return true;
  }

  function enqueueText(text, priority = false) {
    const normalized = normalizeText(text);
    if (!normalized) return;
    stats.allDone = false;

    if (cache.has(normalized)) {
      const cached = cache.get(normalized);
      stats.cacheHit += 1;
      applyTranslationToAll(normalized, cached);
      return;
    }

    if (inFlightTexts.has(normalized)) return;

    if (queuedTexts.has(normalized)) {
      if (priority) reprioritizeQueuedText(normalized);
      return;
    }

    queuedTexts.add(normalized);

    markAllSameText(normalized, sub => {
      if (sub.status === "pending" || sub.status === "failed") {
        updateSubtitleState(sub, "queued");
      }
    });

    if (priority) queue.unshift(normalized);
    else queue.push(normalized);

    stats.currentQueueLength = queue.length;
  }

  async function workerLoop() {
    if (stats.workerRunning) return;
    stats.workerRunning = true;

    while (window.__subtitleTranslatorRunning && !window.__subtitleWorkerAbort) {
      const nextText = queue.shift();
      stats.currentQueueLength = queue.length;

      if (!nextText) {
        if (!stats.allDone) {
          const hasRetryPending = window.__subtitleRetryTimers.size > 0;
          const allResolved =
            stats.translated === stats.total &&
            queue.length === 0 &&
            inFlightTexts.size === 0 &&
            !hasRetryPending;
          if (allResolved) stats.allDone = true;
        }
        await new Promise(r => setTimeout(r, 200));
        continue;
      }

      queuedTexts.delete(nextText);
      inFlightTexts.add(nextText);

      markAllSameText(nextText, sub => {
        if (sub.status !== "done") updateSubtitleState(sub, "translating");
      });

      try {
        const translation = await translateRateLimited(nextText);
        cache.set(nextText, translation);
        applyTranslationToAll(nextText, translation);
        stats.lastTranslatedText = nextText;
      } catch (e) {
        console.warn("Translation failed:", nextText, e);
        markFailedForAll(nextText, e);
      } finally {
        inFlightTexts.delete(nextText);
        stats.currentQueueLength = queue.length;
      }
    }

    stats.workerRunning = false;
  }

  let cursor = 0;

  function getSubtitleIndexByTime(t) {
    const tol = CONFIG.MATCH_TOLERANCE;

    while (cursor < subtitles.length - 1 && t > subtitles[cursor].end + tol) cursor++;
    while (cursor > 0 && t < subtitles[cursor].start - tol) cursor--;

    const s = subtitles[cursor];
    if (s && t >= s.start - tol && t <= s.end + tol) return cursor;

    for (let i = Math.max(0, cursor - 5); i <= Math.min(subtitles.length - 1, cursor + 5); i++) {
      const x = subtitles[i];
      if (t >= x.start - tol && t <= x.end + tol) {
        cursor = i;
        return i;
      }
    }

    return -1;
  }

  function getBestTranslation(sub) {
    if (!sub || !sub.text) return null;
    if (sub.translation) return sub.translation;

    const cached = cache.get(sub.text);
    if (cached) {
      updateSubtitleState(sub, "done", { translation: cached, error: null });
      return cached;
    }

    return null;
  }

  function renderSubtitle(sub) {
    let nextText = "";

    if (sub) {
      const en = sub.text || "";
      const translation = getBestTranslation(sub);

      if (translation) {
        nextText = `${en}\n${translation}`;
      } else if (sub.status === "failed") {
        // Do not leave the subtitle stuck in a loading state after failures.
        nextText = `${en}\n(Translation failed)`;
      } else {
        nextText = `${en}\n⏳ Translating...`;
      }
    }

    // Avoid DOM writes when nothing changes; this is one of the hottest paths during playback.
    if (nextText !== lastRenderedSubtitleText) {
      subtitleDiv.innerText = nextText;
      lastRenderedSubtitleText = nextText;
    }
  }

  function requestImmediateTranslationForIndex(index) {
    const sub = subtitles[index];
    if (!sub || !sub.text) return;

    if (sub.translation) return;

    const cached = cache.get(sub.text);
    if (cached) {
      updateSubtitleState(sub, "done", { translation: cached, error: null });
      return;
    }

    if (sub.status === "translating") return;

    enqueueText(sub.text, true);
  }

  function boostLookahead(index) {
    for (let i = 0; i <= CONFIG.LOOKAHEAD_COUNT; i++) {
      const targetIndex = index + i;
      const s = subtitles[targetIndex];
      if (!s || !s.text) continue;

      if (s.translation) continue;

      const cached = cache.get(s.text);
      if (cached) {
        updateSubtitleState(s, "done", { translation: cached, error: null });
        continue;
      }

      enqueueText(s.text, i === 0);
    }
  }

  function enqueueWindowAround(index, forward = CONFIG.PRIORITY_FORWARD, backward = CONFIG.PRIORITY_BACKWARD) {
    if (index < 0) return;

    const current = subtitles[index];
    if (current?.text) enqueueText(current.text, true);

    for (let i = 1; i <= forward; i++) {
      const s = subtitles[index + i];
      if (s?.text) enqueueText(s.text, true);
    }

    for (let i = 1; i <= backward; i++) {
      const s = subtitles[index - i];
      if (s?.text) enqueueText(s.text, true);
    }
  }

  function enqueueRemainingFrom(index) {
    const orderedTexts = [];
    const localSeen = new Set();

    for (let i = index; i < subtitles.length; i++) {
      const text = subtitles[i]?.text;
      if (text && !localSeen.has(text)) {
        localSeen.add(text);
        orderedTexts.push(text);
      }
    }

    for (let i = 0; i < index; i++) {
      const text = subtitles[i]?.text;
      if (text && !localSeen.has(text)) {
        localSeen.add(text);
        orderedTexts.push(text);
      }
    }

    for (const text of orderedTexts) {
      if (!scheduledUniqueTexts.has(text)) {
        scheduledUniqueTexts.add(text);
        enqueueText(text, false);
      }
    }
  }

  const startIndex = getSubtitleIndexByTime(video.currentTime);
  if (startIndex !== -1) {
    console.log("✅ Built priority queue from current playback position, index =", startIndex);
    enqueueWindowAround(startIndex, CONFIG.PRIORITY_FORWARD, CONFIG.PRIORITY_BACKWARD);
    enqueueRemainingFrom(startIndex);
    stats.lastPriorityIndex = startIndex;
  } else {
    console.log("⚠️ No subtitle matched the current playback time, falling back to the full queue");
    for (const text of textToIndices.keys()) {
      scheduledUniqueTexts.add(text);
      enqueueText(text, false);
    }
  }

  workerLoop();

  window.__subtitleOnSeeked = () => {
    const idx = getSubtitleIndexByTime(video.currentTime);
    console.log("⏩ User seeked to:", video.currentTime, "index:", idx);

    if (idx !== -1) {
      enqueueWindowAround(idx, CONFIG.PRIORITY_FORWARD, CONFIG.PRIORITY_BACKWARD);
      enqueueRemainingFrom(idx);
      stats.lastPriorityIndex = idx;
    }
  };

  video.addEventListener("seeked", window.__subtitleOnSeeked);

  let lastIndex = -1;

  function renderProgress() {
    const uniqueTotal = textToIndices.size;

    progressDiv.innerText =
`Translation Progress
--------------------------------
VTT: ${vttUrl.slice(0, 72)}${vttUrl.length > 72 ? "..." : ""}
Total number of subtitles: ${stats.total}
Unique text count: ${uniqueTotal}

Translated: ${stats.translated}/${stats.total} (${percent(stats.translated, stats.total)})
Unique completed: ${stats.uniqueDone}/${uniqueTotal} (${percent(stats.uniqueDone, uniqueTotal)})
Failure: ${stats.failed}
Cache hits: ${stats.cacheHit}
Requests sent: ${stats.requested}
Queue remaining: ${queue.length}
In flight: ${inFlightTexts.size}
Cache size: ${cache.size()}
Current priority center: ${stats.lastPriorityIndex}
Running time: ${elapsedMs(Date.now() - stats.startedAt)}

Current subtitle:
${stats.activeText ? stats.activeText.slice(0, 90) : "(none)"}

Recently completed:
${stats.lastTranslatedText ? stats.lastTranslatedText.slice(0, 90) : "(none)"}

Status: ${stats.allDone ? "Translation complete" : "Translating"}`;
  }

  window.__subtitleTimer = setInterval(() => {
    if (!window.__subtitleTranslatorRunning) return;

    const t = video.currentTime;
    const index = getSubtitleIndexByTime(t);

    if (index === -1) {
      renderSubtitle(null);
      return;
    }

    const sub = subtitles[index];
    stats.activeText = sub.text;

    if (index !== lastIndex) {
      lastIndex = index;
      requestImmediateTranslationForIndex(index);
      boostLookahead(index);
    }

    renderSubtitle(sub);
  }, CONFIG.UI_UPDATE_INTERVAL);

  window.__progressTimer = setInterval(() => {
    if (!window.__subtitleTranslatorRunning) return;
    // Skip string building and DOM updates while the panel is hidden.
    if (!isProgressVisible) return;
    renderProgress();
  }, CONFIG.PROGRESS_UPDATE_INTERVAL);

  console.log("Script started");
  console.log("Stop the script with: window.__subtitleTranslatorCleanup()");
})();
